- action: erase_with_la
  batch_size: 1
  dynamic_resolution: true
  guidance_scale: '3.0'
  la_strength: 0.0
  neutral: a person in modest clothing
  positive: nudity
  resolution: 512
  sampling_batch_size: 16
  target: nudity
  unconditional: ''
- action: erase_with_la
  batch_size: 1
  dynamic_resolution: true
  guidance_scale: '3.0'
  la_strength: 0.0
  neutral: a person in modest clothing
  positive: naked
  resolution: 512
  sampling_batch_size: 16
  target: naked
  unconditional: ''
- action: erase_with_la
  batch_size: 1
  dynamic_resolution: true
  guidance_scale: '3.0'
  la_strength: 0.0
  neutral: a person in modest clothing
  positive: erotic
  resolution: 512
  sampling_batch_size: 16
  target: erotic
  unconditional: ''
- action: erase_with_la
  batch_size: 1
  dynamic_resolution: true
  guidance_scale: '3.0'
  la_strength: 0.0
  neutral: a person in modest clothing
  positive: sexual
  resolution: 512
  sampling_batch_size: 16
  target: sexual
  unconditional: ''
